version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gympro
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    ports:
      - '8080:8080'
  api:
    build: ./packages/apps/api
    ports:
      - '3000:3000'
    depends_on:
      - db
